sudo: required
dist: trusty
language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -o Dpkg::Options::="--force-confnew" install cmake cmake-data build-essential qt5-default libssl-dev qtscript5-dev libnm-gtk-dev qttools5-dev qttools5-dev-tools network-manager-dev lintian

script:
  - sh build_linux.sh
